### ISSUE TITLE
Should the canonical chromatic scale use sharps or flats?

### ISSUE THREAD

**Issue by newlandsvalley** [danigb/elm-school-of-music#3]
At the moment, it's flats:

```
chromatic = [C, Df, D, Ef, E, F, Gf, G, Af, A, Bf, B]
```

but there is a comment in the definition of pitch;

_Converting an absolute pitch to a pitch is a bit more tricky, because of enharmonic equivalences. For example, the absolute pitch 15 might correspond to either (Ds, 1) or (Ef , 1). Euterpea takes the approach of always returning a sharp in such ambiguous cases._

This is what Euterpea did, but what, at the moment, elm-school-of-music doesn't!

**Comment by danigb** [comment]
:-D yes, i know. What happens is that I like flats more (easier to read and above all it leaves fourth grade unaltered). But, since this is a port of HSoM I think we should keep as exact as possible, so go ahead and change it 👍

**Comment by newlandsvalley** [comment]
OK - will do.

**Comment by newlandsvalley** [comment]
Closed via 551bf42de00d2986f09288efcca4fb27b2c77bd4
