### ISSUE TITLE
Do we want to make Dur a Rational?

### ISSUE THREAD

**Issue by newlandsvalley** [danigb/elm-school-of-music#4]
This is what Euterpea does, but at the moment we use floats.  I guess arithmetic is probably better with Rationals. We can use http://package.elm-lang.org/packages/imeckler/ratio/2.0.1/Ratio.  However, it makes sample programs really turgid to write for whole number durations.  For example

    Rest 3

becomes

    Rest (fromInt 3)    

and
    
    Note 3 (C, 4)

becomes

    Note (fromInt 3) (C 4)

conversely

    Rest 0.333333

is awkward and becomes

    Rest (over 1 3)

or

    Rest (1 `over` 3)

**Comment by danigb** [comment]
I would go with rational with no doubt (floats in js are broken). But I started with floats to simplify. Feel free to change it. 👍

**Comment by newlandsvalley** [comment]
Fixed via b95b7c58cc139eccc745f79beef6df8af754b56c
