### ISSUE TITLE
Should we fork imeckler/Ratio?

### ISSUE THREAD

**Issue by newlandsvalley** [danigb/elm-school-of-music#7]
I'm concerned about a couple of things:

1) The Rational constructor is hidden.  You can only build one by using one of the constructor functions - this means Rationals cannot be used straightforwardly in pattern-matching.  The reason is that if you expose it, you can create a rational of the form:

```
Rational 2 6
```

which should, of course, be represented as _Rational 1 3_.  I'm not sure if this would lead to any downstream problems - I can't think of any at the moment.  Note that in Haskell you can build one using  _2 % 6_ which automatically reduces to _1 % 3_.

2) It seems a bit lightweight in the combinators it offers - missing max, min, lt, gt, eq etc. etc.

**Comment by newlandsvalley** [comment]
I'm beginning to change my mind about exposing the constructor - but for a different reason. I think we need to do the following form of normalisation (not attempted by imeckler/Ratio) - probably in the _over_ function. cf Haskell:

```
(-1) % 2  => (-1) % 2  
1 % (-2) => (-1) % 2
(-1) % (-2) => 1 % 2
```

Basically the denominator should always be a positive integer.  Not too sure yet how to prevent 

```
Rational 1 0
```

**Comment by newlandsvalley** [comment]
I've decided to fork it  with the experimental https://github.com/newlandsvalley/ratio. We need, in particular, a terse form of mixed-type arithmetic.

**Comment by danigb** [comment]
Great! I'll look at it 👍👏

**Comment by newlandsvalley** [comment]
Now resolved.  My fork has now been adopted by the elm-community - https://github.com/elm-community/ratio.  The latest PR uses this version.

**Comment by danigb** [comment]
Congrats! I'm grad your work was adopted by the elm community! 👍
